# Generated by Django 5.1.7 on 2025-04-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_alter_conversionhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionhistory',
            name='updated_at',
        ),
    ]
